# Generated by Django 4.2.2 on 2023-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education_lien_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='lien_entreprise',
            field=models.URLField(blank=True, null=True),
        ),
    ]
