# Generated by Django 4.2.2 on 2023-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_experience_lien_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='niveau',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
