# Generated by Django 4.2.2 on 2023-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_competence_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='langue',
            name='niveau',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
